version = 1

[*]
jinja = true
# Increase log-verbosity to 5 to see the raw RPC chatter between server and harness
log-verbosity = 4
flash-attn = on

# Reduce max parallel connections from 4 to 1; saves ~800 MiB RAM on larger models
parallel = 1
kv-unified = true

# Max prompt cache in host RAM, in MiB
cache-ram = 8192
# A handful checkpoints is plenty for mid-context rollback.
ctx-checkpoints = 4

ngl = 99

# Prevent infinite loops in the inner monologue
reasoning-budget = 8192
reasoning-budget-message = "My reasoning budget is exhausted, but I have enough information to answer directly now."

[Qwen3.8-27B]
# Requires >=24 GB VRAM: RTX 3090, RTX 4090, or RTX 5090
hf = byteshape/Qwen3.8-27B-GGUF:Qwen3.8-27B-IQ4_XS-3.84bpw
image-min-tokens = 1024  # Suppress Qwen-specific warning

ctx-size = 262144
cache-type-k = kvarn5
cache-type-v = kvarn5

# no-mmproj-offload = true  # Keep vision tower in host RAM (-1184 MiB VRAM)
# no-mmproj = true  # Disable vision entirely to save RAM

# MTP drafter
spec-type = draft-mtp
spec-draft-ngl = 99
spec-draft-n-max = 3

# Thinking mode
temperature = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

[Occamy-1.0]
# Requires >= 10 GB VRAM + 16 GB host RAM
hf = bartowski/occamy-ai_occamy-1.0-GGUF:IQ4_XS
image-min-tokens = 1024  # Suppress Qwen-specific warning

ctx-size = 262144
cache-type-k = kvarn4
cache-type-v = kvarn4

n-cpu-moe = 99
# no-mmproj-offload = true  # Keep vision tower in host RAM
# no-mmproj = true  # Disable vision entirely to save RAM

temperature = 0.6
top-p = 0.95
presence-penalty = 1.5

[MiniCPM5-2B]
# Requires >= 6 GB VRAM
# It's small enough that it can run without video acceleration
hf = bartowski/MiniCPM5-2B-GGUF:Q6_K

ctx-size = 131072
cache-type-k = q5_0
cache-type-v = q3_0
kv-tail-tokens = 1024

spec-type = draft-dspark
spec-draft-hf = openbmb/MiniCPM5-2B-DSpark-GGUF:DSpark
spec-draft-ngl = 99
spec-draft-n-max = 7

temperature = 1.0
top-p = 0.95
min-p = 0.0
# If you encounter repetitive outputs
; repeat-penalty = 1.05
